<a href="https://colab.research.google.com/github/SUCCESSneeded/drive-seaborn/blob/main/sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import sklearn as sk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LinearRegression

In [21]:
x=np.array([[1,2],[3,4],[5,6],[7,8]])
y=np.dot(x,np.array([1,2]))+3
reg=LinearRegression().fit(x,y)
print(reg.score(x,y))
print(reg.coef_)
print(reg.intercept_)
print(reg.predict(np.array([[9,10]])))
reg.get_params()

1.0
[1.5 1.5]
3.5000000000000036
[32.]

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [22]:
url="https://raw.githubusercontent.com/SUCCESSneeded/practice/refs/heads/main/E%20Commerce%20Dataset%20(1).csv?token=GHSAT0AAAAAAEMA73STFK2PGTC6TROARITI2W4RRWA"
df=pd.read_csv(url)
print(df.head())
df.shape

   CustomerID  Churn  Tenure PreferredLoginDevice  CityTier  WarehouseToHome  \
0       50001      1     4.0         Mobile Phone         3              6.0
1       50002      1     NaN                Phone         1              8.0
2       50003      1     NaN                Phone         1             30.0
3       50004      1     0.0                Phone         3             15.0
4       50005      1     0.0                Phone         1             12.0

  PreferredPaymentMode  Gender  HourSpendOnApp  NumberOfDeviceRegistered  \
0           Debit Card  Female             3.0                         3
1                  UPI    Male             3.0                         4
2           Debit Card    Male             2.0                         4
3           Debit Card    Male             2.0                         4
4                   CC    Male             NaN                         3

     PreferedOrderCat  SatisfactionScore MaritalStatus  NumberOfAddress  \
0  Laptop & Accessory                  2        Single                9
1              Mobile                  3        Single                7
2              Mobile                  3        Single                6
3  Laptop & Accessory                  5        Single                8
4              Mobile                  5        Single                3

   Complain  OrderAmountHikeFromlastYear  CouponUsed  OrderCount  \
0         1                         11.0         1.0         1.0
1         1                         15.0         0.0         1.0
2         1                         14.0         0.0         1.0
3         0                         23.0         0.0         1.0
4         0                         11.0         1.0         1.0

   DaySinceLastOrder  CashbackAmount
0                5.0             160
1                0.0             121
2                3.0             120
3                3.0             134
4                3.0             130

(5630, 20)

In [23]:
churn=df.dropna()
print(churn.shape)

(3774, 20)

In [24]:
churn.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,160
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134
5,50006,1,0.0,Computer,1,22.0,Debit Card,Female,3.0,5,Mobile Phone,5,Single,2,1,22.0,4.0,6.0,7.0,139
11,50012,1,11.0,Mobile Phone,1,6.0,Debit Card,Male,3.0,4,Fashion,3,Single,10,1,13.0,0.0,1.0,0.0,154
12,50013,1,0.0,Phone,1,11.0,COD,Male,2.0,3,Mobile,3,Single,2,1,13.0,2.0,2.0,2.0,134

In [25]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3774 entries, 0 to 5629
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CustomerID                   3774 non-null   int64
 1   Churn                        3774 non-null   int64
 2   Tenure                       3774 non-null   float64
 3   PreferredLoginDevice         3774 non-null   object
 4   CityTier                     3774 non-null   int64
 5   WarehouseToHome              3774 non-null   float64
 6   PreferredPaymentMode         3774 non-null   object
 7   Gender                       3774 non-null   object
 8   HourSpendOnApp               3774 non-null   float64
 9   NumberOfDeviceRegistered     3774 non-null   int64
 10  PreferedOrderCat             3774 non-null   object
 11  SatisfactionScore            3774 non-null   int64
 12  MaritalStatus                3774 non-null   object
 13  NumberOfAddress              3774 non-null   int64
 14  Complain                     3774 non-null   int64
 15  OrderAmountHikeFromlastYear  3774 non-null   float64
 16  CouponUsed                   3774 non-null   float64
 17  OrderCount                   3774 non-null   float64
 18  DaySinceLastOrder            3774 non-null   float64
 19  CashbackAmount               3774 non-null   int64
dtypes: float64(7), int64(8), object(5)
memory usage: 619.2+ KB

In [26]:
from sklearn.preprocessing import LabelEncoder as le

In [27]:
churn['PreferredLoginDevice']=le().fit_transform(churn['PreferredLoginDevice'])
churn['PreferredPaymentMode']=le().fit_transform(churn['PreferredPaymentMode'])
churn['PreferedOrderCat']=le().fit_transform(churn['PreferedOrderCat'])
churn['MaritalStatus']=le().fit_transform(churn['MaritalStatus'])
churn['Gender']=le().fit_transform(churn['Gender'])
churn.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,1,3,6.0,4,0,3.0,3,2,2,2,9,1,11.0,1.0,1.0,5.0,160
3,50004,1,0.0,2,3,15.0,4,1,2.0,4,2,5,2,8,0,23.0,0.0,1.0,3.0,134
5,50006,1,0.0,0,1,22.0,4,0,3.0,5,4,5,2,2,1,22.0,4.0,6.0,7.0,139
11,50012,1,11.0,1,1,6.0,4,1,3.0,4,0,3,2,10,1,13.0,0.0,1.0,0.0,154
12,50013,1,0.0,2,1,11.0,1,1,2.0,3,3,3,2,2,1,13.0,2.0,2.0,2.0,134

In [37]:
url2="https://raw.githubusercontent.com/SUCCESSneeded/practice/refs/heads/main/german_credit_data.csv?token=GHSAT0AAAAAAEMA73SSM3A6GWNHO4X77Q2K2W4R66Q"
df2=pd.read_csv(url2)
print(df2.head())

   Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little
1           1   22  female    2     own          little         moderate
2           2   49    male    1     own          little              NaN
3           3   45    male    2    free          little           little
4           4   53    male    2    free          little           little

   Credit amount  Duration              Purpose  Risk
0           1169         6             radio/TV  good
1           5951        48             radio/TV   bad
2           2096        12            education  good
3           7882        42  furniture/equipment  good
4           4870        24                  car   bad

In [45]:
df2.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64
 4   Housing           1000 non-null   object
 5   Saving accounts   817 non-null    object
 6   Checking account  606 non-null    object
 7   Credit amount     1000 non-null   int64
 8   Duration          1000 non-null   int64
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

(5630, 20)

In [66]:
german=df2.drop(columns=['Saving accounts', 'Checking account','Purpose'],inplace=True)
german=df2.dropna()
print(german.shape)
german['Age']=german['Age'].fillna(german['Age'].mean)
german.info()

(1000, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     1000 non-null   int64
 1   Age            1000 non-null   int64
 2   Sex            1000 non-null   object
 3   Job            1000 non-null   int64
 4   Housing        1000 non-null   object
 5   Credit amount  1000 non-null   int64
 6   Duration       1000 non-null   int64
 7   Risk           1000 non-null   object
dtypes: int64(5), object(3)
memory usage: 62.6+ KB

In [67]:
german['Housing']=le().fit_transform(german['Housing'])
german['Sex']=le().fit_transform(german['Sex'])
german['Risk']=le().fit_transform(german['Risk'])
print(german.head())
german.shape

   Unnamed: 0  Age  Sex  Job  Housing  Credit amount  Duration  Risk
0           0   67    1    2        1           1169         6     1
1           1   22    0    2        1           5951        48     0
2           2   49    1    1        1           2096        12     1
3           3   45    1    2        0           7882        42     1
4           4   53    1    2        0           4870        24     0

(1000, 8)

In [69]:
corr=german.corr()
print(corr[(corr)>0.1])

               Unnamed: 0       Age       Sex       Job  Housing  \
Unnamed: 0            1.0       NaN       NaN       NaN      NaN
Age                   NaN  1.000000  0.161694       NaN      NaN
Sex                   NaN  0.161694  1.000000       NaN      NaN
Job                   NaN       NaN       NaN  1.000000      NaN
Housing               NaN       NaN       NaN       NaN      1.0
Credit amount         NaN       NaN       NaN  0.285385      NaN
Duration              NaN       NaN       NaN  0.210910      NaN
Risk                  NaN       NaN       NaN       NaN      NaN

               Credit amount  Duration  Risk
Unnamed: 0               NaN       NaN   NaN
Age                      NaN       NaN   NaN
Sex                      NaN       NaN   NaN
Job                 0.285385  0.210910   NaN
Housing                  NaN       NaN   NaN
Credit amount       1.000000  0.624984   NaN
Duration            0.624984  1.000000   NaN
Risk                     NaN       NaN   1.0

In [70]:
x=german.drop(columns=['Risk'])
y=german['Risk']

In [71]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=32)

In [75]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [80]:
y_pred=model.predict(x_test)
print(y_pred)
y_predcounts=pd.Series(y_pred).value_counts()
print(y_test)
print(y_predcounts)
pd.Series(y_test).value_counts()

[1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
632    1
687    1
833    1
182    0
831    0
      ..
258    1
118    0
279    1
458    1
301    0
Name: Risk, Length: 200, dtype: int64
1    185
0     15
Name: count, dtype: int64

Risk
1    134
0     66
Name: count, dtype: int64

In [82]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))

0.685
              precision    recall  f1-score   support

           0       0.60      0.14      0.22        66
           1       0.69      0.96      0.80       134

    accuracy                           0.69       200
   macro avg       0.65      0.55      0.51       200
weighted avg       0.66      0.69      0.61       200

[[  9  57]
 [  6 128]]

In [83]:
print(accuracy_score(y_test,y_pred))

0.685

In [84]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.60      0.14      0.22        66
           1       0.69      0.96      0.80       134

    accuracy                           0.69       200
   macro avg       0.65      0.55      0.51       200
weighted avg       0.66      0.69      0.61       200